const { contextBridge, ipcRenderer } = require('electron');

// 所有 on* 订阅统一经此注册，并回传退订函数：渲染层若重新初始化，
// 不退订就会叠加监听器，同一条通知被回调多次。
function subscribe(channel, handler) {
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld('notchAPI', {
  platform: process.platform,
  setMode: (mode) => ipcRenderer.invoke('window:set-mode', mode),
  beginCollapse: () => ipcRenderer.invoke('window:begin-collapse'),
  setCollapsedHover: (hovering) => ipcRenderer.send('window:set-collapsed-hover', hovering === true),
  setTab: (tab) => ipcRenderer.invoke('window:set-tab', tab),
  ensureMicrophone: () => ipcRenderer.invoke('media:microphone'),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  openPrivacySettings: (pane) => ipcRenderer.invoke('shell:open-privacy-settings', pane),
  searchWeatherCities: (query) => ipcRenderer.invoke('home:weather-search', query),
  getHomeWeather: (location) => ipcRenderer.invoke('home:weather', location),
  getFinanceSettings: () => ipcRenderer.invoke('finance:get-settings'),
  setFinanceProvider: (payload) => ipcRenderer.invoke('finance:set-provider', payload),
  setFinanceRefreshInterval: (seconds) => ipcRenderer.invoke('finance:set-refresh-interval', seconds),
  setFinanceActivity: (payload) => ipcRenderer.invoke('finance:set-activity', payload),
  onFinanceUpdate: (cb) => subscribe('finance:update', (event, payload) => cb(payload)),
  testFinanceProvider: (providerId) => ipcRenderer.invoke('finance:test-provider', providerId),
  refreshFinanceCache: () => ipcRenderer.invoke('finance:refresh'),
  getFinanceOverview: (payload) => ipcRenderer.invoke('finance:overview', payload),
  getFinanceRanking: (payload) => ipcRenderer.invoke('finance:ranking', payload),
  getFinanceQuotes: (payload) => ipcRenderer.invoke('finance:quotes', payload),
  getFinanceHistory: (payload) => ipcRenderer.invoke('finance:history', payload),
  getFinanceFundamentals: (payload) => ipcRenderer.invoke('finance:fundamentals', payload),
  cancelFinanceRequest: (requestId) => ipcRenderer.invoke('finance:cancel', requestId),
  searchFinanceAssets: (query, requestId) => ipcRenderer.invoke('finance:search', { query, requestId }),
  getHomeMusicLibrary: () => ipcRenderer.invoke('home:music-library'),
  setHomeMusicMode: (mode) => ipcRenderer.invoke('home:music-mode', mode),
  selectHomeMusicPlaylist: (payload) => ipcRenderer.invoke('home:music-select-playlist', payload),
  refreshHomeMusicSource: (sourceId) => ipcRenderer.invoke('home:music-refresh-source', sourceId),
  addHomeMusicSource: (payload) => ipcRenderer.invoke('home:music-add-source', payload),
  removeHomeMusicSource: (sourceId) => ipcRenderer.invoke('home:music-remove-source', sourceId),
  browseHomeMusicCategories: (payload) => ipcRenderer.invoke('home:music-browse-categories', payload),
  searchHomeMusicPlaylists: (payload) => ipcRenderer.invoke('home:music-search-playlists', payload),
  browseHomeMusicCategory: (payload) => ipcRenderer.invoke('home:music-browse-category', payload),
  browseHomeMusicRecommend: (payload) => ipcRenderer.invoke('home:music-browse-recommend', payload),
  browseHomeMusicUserPlaylists: (payload) => ipcRenderer.invoke('home:music-browse-user-playlists', payload),
  selectHomeMusicOnlinePlaylist: (payload) => ipcRenderer.invoke('home:music-select-online-playlist', payload),
  chooseHomeMusicFiles: () => ipcRenderer.invoke('home:music-choose-files'),
  chooseHomeMusicFolder: () => ipcRenderer.invoke('home:music-choose-folder'),
  addHomeMusicUrl: (payload) => ipcRenderer.invoke('home:music-add-network', payload),
  removeHomeMusicTrack: (trackId) => ipcRenderer.invoke('home:music-remove', trackId),
  loadHomeMusicTrack: (trackId) => ipcRenderer.invoke('home:music-load', trackId),
  loadHomeMusicCover: (trackId) => ipcRenderer.invoke('home:music-cover', trackId),
  inspectLink: (url) => ipcRenderer.invoke('links:inspect', url),
  listWindows: () => ipcRenderer.invoke('windows:list'),
  focusWindow: (windowId) => ipcRenderer.invoke('windows:focus', windowId),
  saveRecording: (payload) => ipcRenderer.invoke('recordings:save', payload),
  readRecording: (audioPath) => ipcRenderer.invoke('recordings:read', audioPath),
  deleteRecording: (audioPath) => ipcRenderer.invoke('recordings:delete', audioPath),
  revealRecording: (audioPath) => ipcRenderer.invoke('recordings:reveal', audioPath),
  organizeMaterial: (payload) => ipcRenderer.invoke('smart:organize-material', payload),
  runAI: (payload) => ipcRenderer.invoke('ai:run', payload),
  cancelAI: (requestId) => ipcRenderer.invoke('ai:cancel', requestId),
  testAIProvider: (slot = 'content') => ipcRenderer.invoke('ai:test-provider', { slot }),
  getAIDiagnostics: () => ipcRenderer.invoke('ai:get-diagnostics'),
  clearAIDiagnostics: () => ipcRenderer.invoke('ai:clear-diagnostics'),
  acknowledgeAIMigration: () => ipcRenderer.invoke('ai:ack-migration'),
  onAIEvent: (cb) => subscribe('ai:event', (event, payload) => cb(payload)),
  listCredentials: () => ipcRenderer.invoke('credentials:list'),
  getCredential: (id) => ipcRenderer.invoke('credentials:get', id),
  saveCredential: (payload) => ipcRenderer.invoke('credentials:save', payload),
  deleteCredentials: (ids) => ipcRenderer.invoke('credentials:delete-many', ids),
  copyCredential: (id, field) => ipcRenderer.invoke('credentials:copy', { id, field }),
  getTranscriptionConfig: () => ipcRenderer.invoke('transcription:get-config'),
  setTranscriptionConfig: (config) => ipcRenderer.invoke('transcription:set-config', config),
  startTranscription: () => ipcRenderer.invoke('transcription:start'),
  sendTranscriptionAudio: (bytes) => ipcRenderer.send('transcription:audio', bytes),
  finishTranscription: () => ipcRenderer.invoke('transcription:finish'),
  onTranscriptionEvent: (cb) => subscribe('transcription:event', (event, payload) => cb(payload)),
  listTaskCompletions: () => ipcRenderer.invoke('tasks:recent'),
  scheduleTodoReminders: (items) => ipcRenderer.invoke('todos:schedule-reminders', items),
  notifyPomodoro: (minutes) => ipcRenderer.invoke('pomodoro:notify', minutes),
  onTodoReminder: (cb) => subscribe('todo:reminded', (event, payload) => cb(payload)),
  onEscape: (cb) => subscribe('key:escape', () => cb()),
  onToggleShortcut: (cb) => subscribe('shortcut:toggle-panel', () => cb()),
  onLauncherToggle: (cb) => subscribe('shortcut:toggle-launcher', () => cb()),
  onLauncherClose: (cb) => subscribe('launcher:close', () => cb()),
  launcherSettings: () => ipcRenderer.invoke('launcher:settings'),
  saveLauncherSettings: (settings) => ipcRenderer.invoke('launcher:save-settings', settings),
  finishLauncherFocus: (restore) => ipcRenderer.invoke('launcher:focus', { restore }),
  transferLauncherData: (id, operation) => ipcRenderer.invoke('launcher:extension-data', { id, operation }),
  completeLauncherNavigation: (token, ok) => ipcRenderer.invoke('launcher:navigation-result', { token, ok }),
  launcherIcon: (id) => ipcRenderer.invoke('launcher:icon', { id }),
  queryLauncher: (query, requestId, regexMode = false) => ipcRenderer.invoke('launcher:query', { query, requestId, regexMode }),
  onLauncherPartial: (cb) => subscribe('launcher:partial', (event, payload) => cb(payload)),
  cancelLauncher: () => ipcRenderer.invoke('launcher:cancel'),
  runLauncher: (id, mode = 'default') => ipcRenderer.invoke('launcher:run', { id, mode }),
  openLauncherUrl: (url) => ipcRenderer.invoke('launcher:open-url', { url }),
  listLauncherExtensions: () => ipcRenderer.invoke('launcher:extensions'),
  installLauncherExtension: () => ipcRenderer.invoke('launcher:extension-install'),
  toggleLauncherExtension: (id, enabled) => ipcRenderer.invoke('launcher:extension-toggle', { id, enabled }),
  removeLauncherExtension: (id) => ipcRenderer.invoke('launcher:extension-remove', { id }),
  getHoverSpaceStatus: () => ipcRenderer.invoke('shortcut:hover-space-status'),
  getAppSettings: () => ipcRenderer.invoke('settings:get'),
  setFeature: (featureId, enabled) => ipcRenderer.invoke('settings:set-feature', { featureId, enabled }),
  setDefaultTab: (tab) => ipcRenderer.invoke('settings:set-default-tab', tab),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('settings:set-auto-launch', enabled === true),
  setPanelShortcut: (accelerator) => ipcRenderer.invoke('settings:set-shortcut', accelerator),
  onAppSettingsChanged: (cb) => subscribe('settings:changed', (event, settings) => cb(settings)),
  onRecordShortcut: (cb) => subscribe('app:record-shortcut', () => cb()),
  getWorkspace: () => ipcRenderer.invoke('workspace:get'),
  loadWorkspaceData: () => ipcRenderer.invoke('workspace:load-data'),
  saveWorkspaceData: (storage) => ipcRenderer.invoke('workspace:save-data', storage),
  openWorkspace: () => ipcRenderer.invoke('workspace:open'),
  chooseWorkspace: () => ipcRenderer.invoke('workspace:choose'),
  onWorkspaceChanged: (cb) => subscribe('workspace:changed', (event, info) => cb(info)),
  onCollapseRequest: (cb) => subscribe('window:request-collapse', () => cb()),
  getMetrics: () => ipcRenderer.invoke('window:metrics'),
  onMetricsChanged: (cb) =>
    subscribe('window:metrics-changed', (event, metrics) => cb(metrics)),
  writeClipboard: (entry) => ipcRenderer.invoke('clipboard:write', entry),
  pasteClipboard: (entry) => ipcRenderer.invoke('clipboard:paste', entry),
  readClipImage: (imagePath) => ipcRenderer.invoke('clipboard:readImage', imagePath),
  deleteClipImages: (paths) => ipcRenderer.invoke('clipboard:deleteImages', paths),
  saveNoteImage: (payload) => ipcRenderer.invoke('notes:save-image', payload),
  chooseNoteImages: (noteId) => ipcRenderer.invoke('notes:choose-images', noteId),
  readNoteImage: (imagePath) => ipcRenderer.invoke('notes:read-image', imagePath),
  deleteNoteImages: (noteId) => ipcRenderer.invoke('notes:delete-images', noteId),
  onNewClipEntry: (cb) => subscribe('clipboard:new-entry', (evt, entry) => cb(entry)),
  onOpenClip: (cb) => subscribe('app:open-clip', () => cb()),
  onOpenApiSettings: (cb) => subscribe('app:open-api-settings', () => cb()),
  onTaskNotification: (cb) =>
    subscribe('task-notification:show', (event, notification) => cb(notification)),
  onTaskNotificationQueue: (cb) =>
    subscribe('task-notification:queue', (event, count) => cb(count)),
  onTaskNotificationHide: (cb) =>
    subscribe('task-notification:hide', (event, eventId) => cb(eventId)),
  onTaskCompletion: (cb) =>
    subscribe('task-completion:new', (event, notification) => cb(notification)),
  taskNotificationDismissed: (eventId) =>
    ipcRenderer.send('task-notification:dismissed', eventId),
  activateTaskNotification: (eventId) =>
    ipcRenderer.invoke('task-notification:activate', eventId),
  taskNotificationHover: (paused) =>
    ipcRenderer.send('task-notification:hover', paused === true),
});
